In [1]:
import numpy as np

In [4]:
x = np.array([[1,2,3],[4,5,6]], np.int16)
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [5]:
print(x)

[[1 2 3]
 [4 5 6]]


In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int16)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [7]:
x[0]

array([1, 2, 3], dtype=int16)

In [8]:
print(x[0])

[1 2 3]


In [9]:
x[0,1]

2

In [12]:
x[:2,2]

array([3, 6], dtype=int16)

In [15]:
x[0,1:2]

array([2], dtype=int16)

In [16]:
x[:,0]

array([1, 4, 7], dtype=int16)

In [17]:
x[:,1]

array([2, 5, 8], dtype=int16)

In [18]:
x[:,2]

array([3, 6, 9], dtype=int16)

In [22]:
x[0,:]

array([1, 2, 3], dtype=int16)

In [23]:
x[1,:]

array([4, 5, 6], dtype=int16)