In [1]:
import numpy as np

In [5]:
x = np.array([[-2,-1,0,5],[9,4,5,-7]], np.int8)
x

array([[-2, -1,  0,  5],
       [ 9,  4,  5, -7]], dtype=int8)

In [ ]:
x.shape

(2, 4)

In [7]:
x.ndim

2

In [8]:
x = np.array([[[-2,-1,0,5],[9,4,5,-7]],[[-2,-1,0,5],[9,4,5,-7]]], np.int8)
x


array([[[-2, -1,  0,  5],
        [ 9,  4,  5, -7]],

       [[-2, -1,  0,  5],
        [ 9,  4,  5, -7]]], dtype=int8)

In [9]:
x.shape

(2, 2, 4)

In [10]:
x.ndim

3

In [11]:
x.dtype

dtype('int8')

In [12]:
x.size

16

In [13]:
x.T

array([[[-2, -2],
        [ 9,  9]],

       [[-1, -1],
        [ 4,  4]],

       [[ 0,  0],
        [ 5,  5]],

       [[ 5,  5],
        [-7, -7]]], dtype=int8)

In [14]:
X = x.T
X.shape

(4, 2, 2)