In [30]:
import numpy as np
x = np.empty([5,5], np.uint8)
x

array([[176, 142, 146, 188, 221],
       [  1,   0,   0, 176,  98],
       [ 16, 189, 221,   1,   0],
       [  0, 240, 106,  16, 189],
       [221,   1,   0,   0, 240]], dtype=uint8)

In [32]:
x = np.empty([3,3], np.uint8)
x

array([[ 16, 193,  30],
       [188, 221,   1],
       [  0,   0,   0]], dtype=uint8)

In [33]:
y = np.full((3,3,3), dtype=np.int16, fill_value=5)
y

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]], dtype=int16)

In [34]:
z = np.ones((2,3,5), np.int8)
z

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int8)

In [35]:
t = np.zeros((5,3,2), np.int8)
t

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int8)