In [37]:
import cv2 
import numpy as np

In [38]:
img = cv2.imread("klon.jpg")
img

array([[[163, 171, 188],
        [ 65,  70,  79],
        [ 88,  84,  83],
        ...,
        [203, 202, 211],
        [202, 201, 210],
        [200, 199, 208]],

       [[147, 154, 171],
        [ 54,  56,  67],
        [ 70,  66,  65],
        ...,
        [206, 205, 214],
        [205, 204, 213],
        [204, 203, 212]],

       [[132, 136, 154],
        [ 49,  49,  61],
        [ 63,  58,  57],
        ...,
        [203, 201, 207],
        [203, 201, 207],
        [202, 200, 206]],

       ...,

       [[129, 120, 111],
        [127, 118, 109],
        [126, 117, 108],
        ...,
        [ 84,  79,  80],
        [ 87,  82,  83],
        [ 87,  82,  83]],

       [[129, 120, 111],
        [126, 117, 108],
        [124, 115, 106],
        ...,
        [ 84,  79,  80],
        [ 80,  75,  76],
        [ 86,  81,  82]],

       [[128, 119, 110],
        [124, 115, 106],
        [123, 114, 105],
        ...,
        [ 85,  80,  81],
        [ 81,  76,  77],
        [ 87,  82,  83]]

resmin boyutunu gösterme

In [39]:
dimension = img.shape
dimension

(426, 640, 3)

herhangi bir piksel

In [40]:
color = img[150,200]
color

array([158, 153, 144], dtype=uint8)

In [41]:
color = img[205,250]
color

array([226, 220, 209], dtype=uint8)

In [42]:
color = img[420,500]
color

array([140, 134, 123], dtype=uint8)

pikselin bgr renkleri

In [43]:
blue = img[420,500,0]
blue

140

In [44]:
green = img[420,500,1]
green

134

In [45]:
red = img[420,500,2]
red

123

In [46]:
img[420,500,0] = 250

150x200 pikselindki blue degeri blue1 e eşitledik

itemset kordinatlar ve değiştirilmek istenen renk belirtilir

In [51]:
blue1 = img.item(150,200,0)
img.itemset((150,200,0),50)

In [52]:


cv2.imshow("Klon Asker", img)
cv2.waitKey(0)
cv2.destroyAllWindows()